openapi: 3.0.0
info:
  title: Dummy API
  version: 1.0.0
  description: A dummy Swagger file for demonstration purposes.
servers:
  - url: http://localhost:3000
paths:
  /dummy:
    get:
      summary: Dummy endpoint
      description: Returns a dummy response
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, world!
